### ISSUE TITLE
I am trying to use this software for a minecraft server with UPnP

### ISSUE THREAD

**Issue by koenradar** [Moxeja/UniversalUPnP#22]
Everything seems to work but using a portchecker doesnt show the port as open.
Any clues about what is going wrong.
Came to this software after portminer not working for me.

**Comment by Moxeja** [comment]
Hi, could you open up file explorer and paste this into the address bar: "%appdata%\UniversalUPnP". In there you should find two log files: "uupnp.log" and "uupnp-err-output.log". Could you upload these two files here so I can take a look at them?

**Comment by koenradar** [comment]
Well i circumvented it by accessing the router and port forwarding but thanks for you response (pretty inactive mail so sorry for the late response).
